document.addEventListener('DOMContentLoaded', function () {
    const roomsList = document.getElementById('rooms-list');
    const searchBar = document.getElementById('search-bar');

    const roomsData = [
        { "Building Number": "AJB", "Location": "ADLER JOURNALISM", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "AJB", "Image": "path/to/image1.jpg" },
        { "Building Number": "AJB", "Location": "ADLER JOURNALISM", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "AJB", "Image": "path/to/image2.jpg" },
        { "Building Number": "ASB", "Location": "ADVANCEMENT SERVICES BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "ASB", "Image": "path/to/image3.jpg" },
        { "Building Number": "ABW", "Location": "ART BUILDING WEST", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "ABW", "Image": "path/to/image4.jpg" },
        { "Building Number": "ABW", "Location": "ART BUILDING WEST", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "ABW", "Image": "path/to/image5.jpg" },
        { "Building Number": "BCSB", "Location": "BECKER COMM STUDIES", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "BCSB", "Image": "path/to/image6.jpg" },
        { "Building Number": "BBE", "Location": "BIOLOGY BUILDING EAST", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "BBE", "Image": "path/to/image7.jpg" },
        { "Building Number": "BBE", "Location": "BIOLOGY BUILDING EAST", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "BBE", "Image": "path/to/image8.jpg" },
        { "Building Number": "BBE", "Location": "BIOLOGY BUILDING EAST", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "BBE", "Image": "path/to/image9.jpg" },
        { "Building Number": "BBE", "Location": "BIOLOGY BUILDING EAST", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "BBE", "Image": "path/to/image10.jpg" },
        { "Building Number": "BBE", "Location": "BIOLOGY BUILDING EAST", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "BBE", "Image": "path/to/image11.jpg" },
        { "Building Number": "BB", "Location": "BIOLOGY BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "BB", "Image": "path/to/image12.jpg" },
        { "Building Number": "BB", "Location": "BIOLOGY BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "BB", "Image": "path/to/image13.jpg" },
        { "Building Number": "BB", "Location": "BIOLOGY BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "BB", "Image": "path/to/image14.jpg" },
        { "Building Number": "BHC", "Location": "BLANK HONORS CENTER", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "BHC", "Image": "path/to/image15.jpg" },
        { "Building Number": "BHC", "Location": "BLANK HONORS CENTER", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "BHC", "Image": "path/to/image16.jpg" },
        { "Building Number": "BHC", "Location": "BLANK HONORS CENTER", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "BHC", "Image": "path/to/image17.jpg" },
        { "Building Number": "BSB", "Location": "BOWEN SCIENCE BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "BSB", "Image": "path/to/image18.jpg" },
        { "Building Number": "BSB", "Location": "BOWEN SCIENCE BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "BSB", "Image": "path/to/image19.jpg" },
        { "Building Number": "BSB", "Location": "BOWEN SCIENCE BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "BSB", "Image": "path/to/image20.jpg" },
        { "Building Number": "BSB", "Location": "BOWEN SCIENCE BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "BSB", "Image": "path/to/image21.jpg" },
        { "Building Number": "BSB", "Location": "BOWEN SCIENCE BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "BSB", "Image": "path/to/image22.jpg" },
        { "Building Number": "BSB", "Location": "BOWEN SCIENCE BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "BSB", "Image": "path/to/image23.jpg" },
        { "Building Number": "BH", "Location": "BOWMAN HOUSE", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "BH", "Image": "path/to/image24.jpg" },
        { "Building Number": "BLB", "Location": "BOYD LAW BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "BLB", "Image": "path/to/image25.jpg" },
        { "Building Number": "BLB", "Location": "BOYD LAW BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "BLB", "Image": "path/to/image26.jpg" },
        { "Building Number": "BLB", "Location": "BOYD LAW BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "BLB", "Image": "path/to/image27.jpg" },
        { "Building Number": "BLB", "Location": "BOYD LAW BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "BLB", "Image": "path/to/image28.jpg" },
        { "Building Number": "BLB", "Location": "BOYD LAW BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "BLB", "Image": "path/to/image29.jpg" },
        { "Building Number": "BLB", "Location": "BOYD LAW BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "BLB", "Image": "path/to/image30.jpg" },
        { "Building Number": "B", "Location": "BURGE HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "B", "Image": "path/to/image31.jpg" },
        { "Building Number": "B", "Location": "BURGE HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "B", "Image": "path/to/image32.jpg" },
        { "Building Number": "B", "Location": "BURGE HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "B", "Image": "path/to/image33.jpg" },
        { "Building Number": "B", "Location": "BURGE HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "B", "Image": "path/to/image34.jpg" },
        { "Building Number": "B", "Location": "BURGE HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "B", "Image": "path/to/image35.jpg" },
        { "Building Number": "CALH", "Location": "CALVIN HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CALH", "Image": "path/to/image36.jpg" },
        { "Building Number": "CMF", "Location": "CAMBUS MAINTENANCE FACILITY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CMF", "Image": "path/to/image37.jpg" },
        { "Building Number": "CRWC", "Location": "CAMPUS RECREATION & WELLNESS", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CRWC", "Image": "path/to/image38.jpg" },
        { "Building Number": "CRWC", "Location": "CAMPUS RECREATION & WELLNESS", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CRWC", "Image": "path/to/image39.jpg" },
        { "Building Number": "CRWC", "Location": "CAMPUS RECREATION & WELLNESS", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CRWC", "Image": "path/to/image40.jpg" },
        { "Building Number": "CRWC", "Location": "CAMPUS RECREATION & WELLNESS", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CRWC", "Image": "path/to/image41.jpg" },
        { "Building Number": "CBRB", "Location": "CARVER BIOMEDICAL RESEARCH BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CBRB", "Image": "path/to/image42.jpg" },
        { "Building Number": "CBRB", "Location": "CARVER BIOMEDICAL RESEARCH BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CBRB", "Image": "path/to/image43.jpg" },
        { "Building Number": "CBRB", "Location": "CARVER BIOMEDICAL RESEARCH BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CBRB", "Image": "path/to/image44.jpg" },
        { "Building Number": "CBRB", "Location": "CARVER BIOMEDICAL RESEARCH BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CBRB", "Image": "path/to/image45.jpg" },
        { "Building Number": "CBRB", "Location": "CARVER BIOMEDICAL RESEARCH BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CBRB", "Image": "path/to/image46.jpg" },
        { "Building Number": "CHA", "Location": "CARVER-HAWKEYE ARENA", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CHA", "Image": "path/to/image47.jpg" },
        { "Building Number": "CAT", "Location": "CATLETT RESIDENCE HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CAT", "Image": "path/to/image48.jpg" },
        { "Building Number": "CAT", "Location": "CATLETT RESIDENCE HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CAT", "Image": "path/to/image49.jpg" },
        { "Building Number": "CAT", "Location": "CATLETT RESIDENCE HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CAT", "Image": "path/to/image50.jpg" },
        { "Building Number": "CAT", "Location": "CATLETT RESIDENCE HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CAT", "Image": "path/to/image51.jpg" },
        { "Building Number": "CAT", "Location": "CATLETT RESIDENCE HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CAT", "Image": "path/to/image52.jpg" },
        { "Building Number": "CAT", "Location": "CATLETT RESIDENCE HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CAT", "Image": "path/to/image53.jpg" },
        { "Building Number": "CAT", "Location": "CATLETT RESIDENCE HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CAT", "Image": "path/to/image54.jpg" },
        { "Building Number": "CAT", "Location": "CATLETT RESIDENCE HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CAT", "Image": "path/to/image55.jpg" },
        { "Building Number": "CB", "Location": "CHEMISTRY BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CB", "Image": "path/to/image56.jpg" },
        { "Building Number": "CB", "Location": "CHEMISTRY BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CB", "Image": "path/to/image57.jpg" },
        { "Building Number": "CB", "Location": "CHEMISTRY BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CB", "Image": "path/to/image58.jpg" },
        { "Building Number": "CB", "Location": "CHEMISTRY BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CB", "Image": "path/to/image59.jpg" },
        { "Building Number": "CB", "Location": "CHEMISTRY BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CB", "Image": "path/to/image60.jpg" },
        { "Building Number": "CB", "Location": "CHEMISTRY BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CB", "Image": "path/to/image61.jpg" },
        { "Building Number": "CB", "Location": "CHEMISTRY BUILDING", "Room Number": "W4Omitted Information48A", "Directions": "Omitted Information for Security.", "Abbreviation": "CB", "Image": "path/to/image62.jpg" },
        { "Building Number": "CB", "Location": "CHEMISTRY BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CB", "Image": "path/to/image63.jpg" },
        { "Building Number": "CNB", "Location": "COLLEGE OF NURSING BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CNB", "Image": "path/to/image64.jpg" },
        { "Building Number": "CNB", "Location": "COLLEGE OF NURSING BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CNB", "Image": "path/to/image65.jpg" },
        { "Building Number": "CPB", "Location": "COLLEGE OF PHARMACY BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CPB", "Image": "path/to/image66.jpg" },
        { "Building Number": "CPB", "Location": "COLLEGE OF PHARMACY BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CPB", "Image": "path/to/image67.jpg" },
        { "Building Number": "CPB", "Location": "COLLEGE OF PHARMACY BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CPB", "Image": "path/to/image68.jpg" },
        { "Building Number": "CPB", "Location": "COLLEGE OF PHARMACY BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CPB", "Image": "path/to/image69.jpg" },
        { "Building Number": "CPB", "Location": "COLLEGE OF PHARMACY BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CPB", "Image": "path/to/image70.jpg" },
        { "Building Number": "CPB", "Location": "COLLEGE OF PHARMACY BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CPB", "Image": "path/to/image71.jpg" },
        { "Building Number": "CPB", "Location": "COLLEGE OF PHARMACY BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CPB", "Image": "path/to/image72.jpg" },
        { "Building Number": "CPB", "Location": "COLLEGE OF PHARMACY BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CPB", "Image": "path/to/image73.jpg" },
        { "Building Number": "CPHB", "Location": "COLLEGE OF PUBLIC HEALTH BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CPHB", "Image": "path/to/image74.jpg" },
        { "Building Number": "CPHB", "Location": "COLLEGE OF PUBLIC HEALTH BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CPHB", "Image": "path/to/image75.jpg" },
        { "Building Number": "CPHB", "Location": "COLLEGE OF PUBLIC HEALTH BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CPHB", "Image": "path/to/image76.jpg" },
        { "Building Number": "CPHB", "Location": "COLLEGE OF PUBLIC HEALTH BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CPHB", "Image": "path/to/image77.jpg" },
        { "Building Number": "CPHB", "Location": "COLLEGE OF PUBLIC HEALTH BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CPHB", "Image": "path/to/image78.jpg" },
        { "Building Number": "CPHB", "Location": "COLLEGE OF PUBLIC HEALTH BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CPHB", "Image": "path/to/image79.jpg" },
        { "Building Number": "CPHB", "Location": "COLLEGE OF PUBLIC HEALTH BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CPHB", "Image": "path/to/image80.jpg" },
        { "Building Number": "CPHB", "Location": "COLLEGE OF PUBLIC HEALTH BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CPHB", "Image": "path/to/image81.jpg" },
        { "Building Number": "CPHB", "Location": "COLLEGE OF PUBLIC HEALTH BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CPHB", "Image": "path/to/image82.jpg" },
        { "Building Number": "D", "Location": "DAUM HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "D", "Image": "path/to/image83.jpg" },
        { "Building Number": "D", "Location": "DAUM HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "D", "Image": "path/to/image84.jpg" },
        { "Building Number": "DSB", "Location": "DENTAL SCIENCE SOUTH", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "DSB", "Image": "path/to/image85.jpg" },
        { "Building Number": "DSB", "Location": "DENTAL SCIENCE SOUTH", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "DSB", "Image": "path/to/image86.jpg" },
        { "Building Number": "DSB", "Location": "DENTAL SCIENCE SOUTH", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "DSB", "Image": "path/to/image87.jpg" },
        { "Building Number": "DSB", "Location": "DENTAL SCIENCE SOUTH", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "DSB", "Image": "path/to/image88.jpg" },
        { "Building Number": "DSB", "Location": "DENTAL SCIENCE SOUTH", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "DSB", "Image": "path/to/image89.jpg" },
        { "Building Number": "DSB", "Location": "DENTAL SCIENCE WEST", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "DSB", "Image": "path/to/image90.jpg" },
        { "Building Number": "EMRB", "Location": "ECKSTEIN MEDICAL RESEARCH BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "EMRB", "Image": "path/to/image91.jpg" },
        { "Building Number": "EMRB", "Location": "ECKSTEIN MEDICAL RESEARCH BUILDING", "Room Number": "1Omitted Information18", "Directions": "Omitted Information for Security.", "Abbreviation": "EMRB", "Image": "path/to/image92.jpg" },
        { "Building Number": "EMRB", "Location": "ECKSTEIN MEDICAL RESEARCH BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "EMRB", "Image": "path/to/image93.jpg" },
        { "Building Number": "EMRB", "Location": "ECKSTEIN MEDICAL RESEARCH BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "EMRB", "Image": "path/to/image94.jpg" },
        { "Building Number": "EMRB", "Location": "ECKSTEIN MEDICAL RESEARCH BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "EMRB", "Image": "path/to/image95.jpg" },
        { "Building Number": "EMRB", "Location": "ECKSTEIN MEDICAL RESEARCH BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "EMRB", "Image": "path/to/image96.jpg" },
        { "Building Number": "EMRB", "Location": "ECKSTEIN MEDICAL RESEARCH BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "EMRB", "Image": "path/to/image97.jpg" },
            { "Building Number": "ERF", "Location": "ENGINEERING RESEARCH FACILITY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "ERF", "Image": "path/to/image98.jpg" },
            { "Building Number": "ERF", "Location": "ENGINEERING RESEARCH FACILITY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "ERF", "Image": "path/to/image99.jpg" },
            { "Building Number": "FH", "Location": "FIELD HOUSE", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "FH", "Image": "path/to/image100.jpg" },
            { "Building Number": "FH", "Location": "FIELD HOUSE", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "FH", "Image": "path/to/image101.jpg" },
            { "Building Number": "FH", "Location": "FIELD HOUSE", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "FH", "Image": "path/to/image102.jpg" },
            { "Building Number": "FH", "Location": "FIELD HOUSE", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "FH", "Image": "path/to/image103.jpg" },
            { "Building Number": "FGCH", "Location": "FINKBINE GOLF CLUB HOUSE", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "FGCH", "Image": "path/to/image104.jpg" },
            { "Building Number": "GILH", "Location": "GILMORE HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "GILH", "Image": "path/to/image105.jpg" },
            { "Building Number": "GILH", "Location": "GILMORE HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "GILH", "Image": "path/to/image106.jpg" },
            { "Building Number": "HH", "Location": "HALSEY HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "HH", "Image": "path/to/image107.jpg" },
            { "Building Number": "HA", "Location": "HANCHER AUDITORIUM", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "HA", "Image": "path/to/image108.jpg" },
            { "Building Number": "HA", "Location": "HANCHER AUDITORIUM", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "HA", "Image": "path/to/image109.jpg" },
            { "Building Number": "HA", "Location": "HANCHER AUDITORIUM", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "HA", "Image": "path/to/image110.jpg" },
            { "Building Number": "HA", "Location": "HANCHER AUDITORIUM", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "HA", "Image": "path/to/image111.jpg" },
            { "Building Number": "HLHS", "Location": "HARDIN LIBRARY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "HLHS", "Image": "path/to/image112.jpg" },
            { "Building Number": "HLHS", "Location": "HARDIN LIBRARY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "HLHS", "Image": "path/to/image113.jpg" },
            { "Building Number": "HLHS", "Location": "HARDIN LIBRARY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "HLHS", "Image": "path/to/image114.jpg" },
            { "Building Number": "HTRC", "Location": "HAWKEYE TENNIS & REC COMPLEX", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "HTRC", "Image": "path/to/image115.jpg" },
            { "Building Number": "HTRC", "Location": "HAWKEYE TENNIS & REC COMPLEX", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "HTRC", "Image": "path/to/image116.jpg" },
            { "Building Number": "HTRC", "Location": "HAWKEYE TENNIS & REC COMPLEX", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "HTRC", "Image": "path/to/image117.jpg" },
            { "Building Number": "HTRC", "Location": "HAWKEYE TENNIS & REC COMPLEX", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "HTRC", "Image": "path/to/image118.jpg" },
            { "Building Number": "H", "Location": "HILLCREST HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "H", "Image": "path/to/image119.jpg" },
            { "Building Number": "H", "Location": "HILLCREST HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "H", "Image": "path/to/image120.jpg" },
            { "Building Number": "H", "Location": "HILLCREST HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "H", "Image": "path/to/image121.jpg" },
            { "Building Number": "H", "Location": "HILLCREST HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "H", "Image": "path/to/image122.jpg" },
            { "Building Number": "H", "Location": "HILLCREST HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "H", "Image": "path/to/image123.jpg" },
            { "Building Number": "H", "Location": "HILLCREST HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "H", "Image": "path/to/image124.jpg" },
            { "Building Number": "H", "Location": "HILLCREST HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "H", "Image": "path/to/image125.jpg" },
            { "Building Number": "LOT13", "Location": "HILLCREST NORTH PARKING LOT 13", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "LOT13", "Image": "path/to/image126.jpg" },
            { "Building Number": "IMU", "Location": "IOWA MEMORIAL UNION", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "IMU", "Image": "path/to/image127.jpg" },
            { "Building Number": "IMU", "Location": "IOWA MEMORIAL UNION", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "IMU", "Image": "path/to/image128.jpg" },
            { "Building Number": "IMU", "Location": "IOWA MEMORIAL UNION", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "IMU", "Image": "path/to/image129.jpg" },
            { "Building Number": "ITDC", "Location": "IT DISTRIBUTION CTR", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "ITDC", "Image": "path/to/image130.jpg" },
            { "Building Number": "ITDC", "Location": "IT DISTRIBUTION CTR", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "ITDC", "Image": "path/to/image131.jpg" },
            { "Building Number": "JB", "Location": "JEFFERSON BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "JB", "Image": "path/to/image132.jpg" },
            { "Building Number": "JB", "Location": "JEFFERSON BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "JB", "Image": "path/to/image133.jpg" },
            { "Building Number": "AACC", "Location": "AFRO-AMERICAN CULTURAL CENTER", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "AACC", "Image": "path/to/image134.jpg" },
            { "Building Number": "ERF", "Location": "ENGINEERING RESEARCH FACILITY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "ERF", "Image": "path/to/image135.jpg" },
            { "Building Number": "GFWC", "Location": "Goschke Family Wrestling Training Facility", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "GFWC", "Image": "path/to/image136.jpg" },
            { "Building Number": "CHA", "Location": "CARVER-HAWKEYE ARENA", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CHA", "Image": "path/to/image137.jpg" },
            { "Building Number": "CHA", "Location": "CARVER-HAWKEYE ARENA", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CHA", "Image": "path/to/image138.jpg" },
            { "Building Number": "CHA", "Location": "CARVER-HAWKEYE ARENA", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "CHA", "Image": "path/to/image139.jpg" },
            { "Building Number": "IRA", "Location": "INDEPENDENCE ROAD ANNEX", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "IRA", "Image": "path/to/image140.jpg" },
            { "Building Number": "HFPC", "Location": "HANSEN FOOTBALL PERFORMANCE CTR", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "HFPC", "Image": "path/to/image141.jpg" },
            { "Building Number": "EPB", "Location": "ENGLISH-PHILOSOPHY BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "EPB", "Image": "path/to/image142.jpg" },
            { "Building Number": "KHF", "Location": "KARRO ATHLETIC HALL OF FAME", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "KHF", "Image": "path/to/image143.jpg" },
            { "Building Number": "KHF", "Location": "KARRO ATHLETIC HALL OF FAME", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "KHF", "Image": "path/to/image144.jpg" },
            { "Building Number": "KS", "Location": "KINNICK STADIUM", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "KS", "Image": "path/to/image145.jpg" },
            { "Building Number": "KS", "Location": "KINNICK STADIUM", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "KS", "Image": "path/to/image146.jpg" },
            { "Building Number": "KS", "Location": "KINNICK STADIUM", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "KS", "Image": "path/to/image147.jpg" },
            { "Building Number": "KS", "Location": "KINNICK STADIUM", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "KS", "Image": "path/to/image148.jpg" },
            { "Building Number": "KS", "Location": "KINNICK STADIUM", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "KS", "Image": "path/to/image149.jpg" },
            { "Building Number": "KS", "Location": "KINNICK STADIUM", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "KS", "Image": "path/to/image150.jpg" },
            { "Building Number": "KS", "Location": "KINNICK STADIUM", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "KS", "Image": "path/to/image151.jpg" },
            { "Building Number": "KS", "Location": "KINNICK STADIUM", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "KS", "Image": "path/to/image152.jpg" },
            { "Building Number": "KS", "Location": "KINNICK STADIUM", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "KS", "Image": "path/to/image153.jpg" },
            { "Building Number": "KS", "Location": "KINNICK STADIUM", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "KS", "Image": "path/to/image154.jpg" },
            { "Building Number": "KS", "Location": "KINNICK STADIUM", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "KS", "Image": "path/to/image155.jpg" },
            { "Building Number": "KS", "Location": "KINNICK STADIUM", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "KS", "Image": "path/to/image156.jpg" },
            { "Building Number": "KH", "Location": "KUHL HOUSE", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "KH", "Image": "path/to/image157.jpg" },
            { "Building Number": "LC", "Location": "LINDQUIST CENTER", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "LC", "Image": "path/to/image158.jpg" },
            { "Building Number": "LC", "Location": "LINDQUIST CENTER", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "LC", "Image": "path/to/image159.jpg" },
            { "Building Number": "LC", "Location": "LINDQUIST CENTER", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "LC", "Image": "path/to/image160.jpg" },
            { "Building Number": "LC", "Location": "LINDQUIST CENTER", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "LC", "Image": "path/to/image161.jpg" },
            { "Building Number": "MH", "Location": "MACBRIDE HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "MH", "Image": "path/to/image162.jpg" },
            { "Building Number": "MH", "Location": "MACBRIDE HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "MH", "Image": "path/to/image163.jpg" },
            { "Building Number": "MH", "Location": "MACBRIDE HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "MH", "Image": "path/to/image164.jpg" },
            { "Building Number": "MLH", "Location": "MACLEAN HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "MLH", "Image": "path/to/image165.jpg" },
            { "Building Number": "MLH", "Location": "MACLEAN HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "MLH", "Image": "path/to/image166.jpg" },
            { "Building Number": "LIB", "Location": "MAIN LIBRARY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "LIB", "Image": "path/to/image167.jpg" },
            { "Building Number": "LIB", "Location": "MAIN LIBRARY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "LIB", "Image": "path/to/image168.jpg" },
            { "Building Number": "LIB", "Location": "MAIN LIBRARY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "LIB", "Image": "path/to/image169.jpg" },
            { "Building Number": "LIB", "Location": "MAIN LIBRARY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "LIB", "Image": "path/to/image170.jpg" },
            { "Building Number": "LIB", "Location": "MAIN LIBRARY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "LIB", "Image": "path/to/image171.jpg" },
            { "Building Number": "LIB", "Location": "MAIN LIBRARY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "LIB", "Image": "path/to/image172.jpg" },
            { "Building Number": "LIB", "Location": "MAIN LIBRARY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "LIB", "Image": "path/to/image173.jpg" },
            { "Building Number": "LIB", "Location": "MAIN LIBRARY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "LIB", "Image": "path/to/image174.jpg" },
            { "Building Number": "LIB", "Location": "MAIN LIBRARY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "LIB", "Image": "path/to/image175.jpg" },
            { "Building Number": "M", "Location": "MAYFLOWER HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "M", "Image": "path/to/image176.jpg" },
            { "Building Number": "M", "Location": "MAYFLOWER HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "M", "Image": "path/to/image177.jpg" },
            { "Building Number": "M", "Location": "MAYFLOWER HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "M", "Image": "path/to/image178.jpg" },
            { "Building Number": "M", "Location": "MAYFLOWER HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "M", "Image": "path/to/image179.jpg" },
            { "Building Number": "MERF", "Location": "MEDICAL EDUCATION RESEARCH FACILITY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "MERF", "Image": "path/to/image180.jpg" },
            { "Building Number": "MERF", "Location": "MEDICAL EDUCATION RESEARCH FACILITY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "MERF", "Image": "path/to/image181.jpg" },
            { "Building Number": "MERF", "Location": "MEDICAL EDUCATION RESEARCH FACILITY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "MERF", "Image": "path/to/image182.jpg" },
            { "Building Number": "MERF", "Location": "MEDICAL EDUCATION RESEARCH FACILITY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "MERF", "Image": "path/to/image183.jpg" },
            { "Building Number": "MERF", "Location": "MEDICAL EDUCATION RESEARCH FACILITY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "MERF", "Image": "path/to/image184.jpg" },
            { "Building Number": "MERF", "Location": "MEDICAL EDUCATION RESEARCH FACILITY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "MERF", "Image": "path/to/image185.jpg" },
            { "Building Number": "MERF", "Location": "MEDICAL EDUCATION RESEARCH FACILITY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "MERF", "Image": "path/to/image186.jpg" },
            { "Building Number": "MERF", "Location": "MEDICAL EDUCATION RESEARCH FACILITY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "MERF", "Image": "path/to/image187.jpg" },
            { "Building Number": "MERF", "Location": "MEDICAL EDUCATION RESEARCH FACILITY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "MERF", "Image": "path/to/image188.jpg" },
            { "Building Number": "MERF", "Location": "MEDICAL EDUCATION RESEARCH FACILITY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "MERF", "Image": "path/to/image189.jpg" },
            { "Building Number": "MERF", "Location": "MEDICAL EDUCATION RESEARCH FACILITY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "MERF", "Image": "path/to/image190.jpg" },
            { "Building Number": "MERF", "Location": "MEDICAL EDUCATION RESEARCH FACILITY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "MERF", "Image": "path/to/image191.jpg" },
            { "Building Number": "ML", "Location": "MEDICAL LABORATORIES", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "ML", "Image": "path/to/image192.jpg" },
            { "Building Number": "ML", "Location": "MEDICAL LABORATORIES", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "ML", "Image": "path/to/image193.jpg" },
            { "Building Number": "MTP1", "Location": "MYRIAD TECHNOLOGY PLAZA #1", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "MTP1", "Image": "path/to/image194.jpg" },
            { "Building Number": "MTP2", "Location": "MYRIAD TECHNOLOGY PLAZA #2", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "MTP2", "Image": "path/to/image195.jpg" },
            { "Building Number": "MTP4", "Location": "MYRIAD TECHNOLOGY PLAZA #4", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "MTP4", "Image": "path/to/image196.jpg" },
            { "Building Number": "OSF", "Location": "OAKDALE STUDIO FACILITY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "OSF", "Image": "path/to/image197.jpg" },
            { "Building Number": "PBDB", "Location": "PAPPAJOHN BIOMEDICAL DISCOVERY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "PBDB", "Image": "path/to/image198.jpg" },
            { "Building Number": "PBDB", "Location": "PAPPAJOHN BIOMEDICAL DISCOVERY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "PBDB", "Image": "path/to/image199.jpg" },
            { "Building Number": "PBDB", "Location": "PAPPAJOHN BIOMEDICAL DISCOVERY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "PBDB", "Image": "path/to/image200.jpg" },
            { "Building Number": "PBDB", "Location": "PAPPAJOHN BIOMEDICAL DISCOVERY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "PBDB", "Image": "path/to/image201.jpg" },
            { "Building Number": "PBDB", "Location": "PAPPAJOHN BIOMEDICAL DISCOVERY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "PBDB", "Image": "path/to/image202.jpg" },
            { "Building Number": "PBB", "Location": "PAPPAJOHN BUSINESS BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "PBB", "Image": "path/to/image203.jpg" },
            { "Building Number": "PBB", "Location": "PAPPAJOHN BUSINESS BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "PBB", "Image": "path/to/image204.jpg" },
            { "Building Number": "PBB", "Location": "PAPPAJOHN BUSINESS BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "PBB", "Image": "path/to/image205.jpg" },
            { "Building Number": "PBB", "Location": "PAPPAJOHN BUSINESS BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "PBB", "Image": "path/to/image206.jpg" },
            { "Building Number": "PH", "Location": "PHILLIPS HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "PH", "Image": "path/to/image207.jpg" },
            { "Building Number": "PH", "Location": "PHILLIPS HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "PH", "Image": "path/to/image208.jpg" },
            { "Building Number": "PH", "Location": "PHILLIPS HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "PH", "Image": "path/to/image209.jpg" },
            { "Building Number": "PC", "Location": "POMERANTZ CENTER", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "PC", "Image": "path/to/image210.jpg" },
            { "Building Number": "PC", "Location": "POMERANTZ CENTER", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "PC", "Image": "path/to/image211.jpg" },
            { "Building Number": "PC", "Location": "POMERANTZ CENTER", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "PC", "Image": "path/to/image212.jpg" },
            { "Building Number": "PR", "Location": "PRESIDENTS RESIDENCE", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "PR", "Image": "path/to/image213.jpg" },
            { "Building Number": "PBSB", "Location": "PSYCH AND BRAIN SCIENCES BLDG", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "PBSB", "Image": "path/to/image214.jpg" },
            { "Building Number": "PBSB", "Location": "PSYCH AND BRAIN SCIENCES BLDG", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "PBSB", "Image": "path/to/image215.jpg" },
            { "Building Number": "PPRB", "Location": "PUBLIC POLICY RESEARCH BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "PPRB", "Image": "path/to/image216.jpg" },
            { "Building Number": "SH", "Location": "SCHAEFFER HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "SH", "Image": "path/to/image217.jpg" },
            { "Building Number": "SH", "Location": "SCHAEFFER HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "SH", "Image": "path/to/image218.jpg" },
            { "Building Number": "SH", "Location": "SCHAEFFER HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "SH", "Image": "path/to/image219.jpg" },
        { "Building Number": "SH", "Location": "SCHAEFFER HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "SH", "Image": "path/to/image220.jpg" },
        { "Building Number": "SL", "Location": "SCIENCES LIBRARY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "SL", "Image": "path/to/image221.jpg" },
        { "Building Number": "SC", "Location": "SEAMANS CENTER", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "SC", "Image": "path/to/image222.jpg" },
        { "Building Number": "SC", "Location": "SEAMANS CENTER", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "SC", "Image": "path/to/image223.jpg" },
        { "Building Number": "SC", "Location": "SEAMANS CENTER", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "SC", "Image": "path/to/image224.jpg" },
        { "Building Number": "SC", "Location": "SEAMANS CENTER", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "SC", "Image": "path/to/image225.jpg" },
        { "Building Number": "SC", "Location": "SEAMANS CENTER", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "SC", "Image": "path/to/image226.jpg" },
        { "Building Number": "SC", "Location": "SEAMANS CENTER", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "SC", "Image": "path/to/image227.jpg" },
        { "Building Number": "SC", "Location": "SEAMANS CENTER", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "SC", "Image": "path/to/image228.jpg" },
        { "Building Number": "SC", "Location": "SEAMANS CENTER", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "SC", "Image": "path/to/image229.jpg" },
        { "Building Number": "SC", "Location": "SEAMANS CENTER", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "SC", "Image": "path/to/image230.jpg" },
        { "Building Number": "SC", "Location": "SEAMANS CENTER", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "SC", "Image": "path/to/image231.jpg" },
        { "Building Number": "SLP", "Location": "SPENCE LABS", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "SLP", "Image": "path/to/image232.jpg" },
        { "Building Number": "SLP", "Location": "SPENCE LABS", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "SLP", "Image": "path/to/image233.jpg" },
        { "Building Number": "SMA", "Location": "STANLEY MUSEUM OF ART", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "SMA", "Image": "path/to/image234.jpg" },
        { "Building Number": "SMA", "Location": "STANLEY MUSEUM OF ART", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "SMA", "Image": "path/to/image235.jpg" },
        { "Building Number": "HLI", "Location": "STATE HYGIENIC LABORATORY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "HLI", "Image": "path/to/image236.jpg" },
        { "Building Number": "HLI", "Location": "STATE HYGIENIC LABORATORY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "HLI", "Image": "path/to/image237.jpg" },
        { "Building Number": "HLI", "Location": "STATE HYGIENIC LABORATORY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "HLI", "Image": "path/to/image238.jpg" },
        { "Building Number": "HLI", "Location": "STATE HYGIENIC LABORATORY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "HLI", "Image": "path/to/image239.jpg" },
        { "Building Number": "HLI", "Location": "STATE HYGIENIC LABORATORY", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "HLI", "Image": "path/to/image240.jpg" },
        { "Building Number": "STH", "Location": "STUIT HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "STH", "Image": "path/to/image241.jpg" },
        { "Building Number": "BVC", "Location": "UI BIOVENTURES CENTER", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "BVC", "Image": "path/to/image242.jpg" },
        { "Building Number": "BVC", "Location": "UI BIOVENTURES CENTER", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "BVC", "Image": "path/to/image243.jpg" },
        { "Building Number": "BVC", "Location": "UI BIOVENTURES CENTER", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "BVC", "Image": "path/to/image244.jpg" },
        { "Building Number": "UCC", "Location": "UNIVERSITY CAPITOL CENTRE", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "UCC", "Image": "path/to/image245.jpg" },
        { "Building Number": "UCC", "Location": "UNIVERSITY CAPITOL CENTRE", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "UCC", "Image": "path/to/image246.jpg" },
        { "Building Number": "UCC", "Location": "UNIVERSITY CAPITOL CENTRE", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "UCC", "Image": "path/to/image247.jpg" },
        { "Building Number": "UCC", "Location": "UNIVERSITY CAPITOL CENTRE", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "UCC", "Image": "path/to/image248.jpg" },
        { "Building Number": "UCC", "Location": "UNIVERSITY CAPITOL CENTRE", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "UCC", "Image": "path/to/image249.jpg" },
        { "Building Number": "UCC", "Location": "UNIVERSITY CAPITOL CENTRE", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "UCC", "Image": "path/to/image250.jpg" },
        { "Building Number": "UCC", "Location": "UNIVERSITY CAPITOL CENTRE", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "UCC", "Image": "path/to/image251.jpg" },
        { "Building Number": "USB", "Location": "UNIVERSITY SERVICES BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "USB", "Image": "path/to/image252.jpg" },
        { "Building Number": "USB", "Location": "UNIVERSITY SERVICES BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "USB", "Image": "path/to/image253.jpg" },
        { "Building Number": "VAN", "Location": "VAN ALLEN HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "VAN", "Image": "path/to/image254.jpg" },
        { "Building Number": "VAN", "Location": "VAN ALLEN HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "VAN", "Image": "path/to/image255.jpg" },
        { "Building Number": "VAB", "Location": "VISUAL ARTS BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "VAB", "Image": "path/to/image256.jpg" },
        { "Building Number": "VAB", "Location": "VISUAL ARTS BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "VAB", "Image": "path/to/image257.jpg" },
        { "Building Number": "VAB", "Location": "VISUAL ARTS BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "VAB", "Image": "path/to/image258.jpg" },
        { "Building Number": "VAB", "Location": "VISUAL ARTS BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "VAB", "Image": "path/to/image259.jpg" },
        { "Building Number": "VOX", "Location": "VOXMAN MUSIC BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "VOX", "Image": "path/to/image260.jpg" },
        { "Building Number": "VOX", "Location": "VOXMAN MUSIC BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "VOX", "Image": "path/to/image261.jpg" },
        { "Building Number": "VOX", "Location": "VOXMAN MUSIC BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "VOX", "Image": "path/to/image262.jpg" },
        { "Building Number": "VOX", "Location": "VOXMAN MUSIC BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "VOX", "Image": "path/to/image263.jpg" },
        { "Building Number": "VOX", "Location": "VOXMAN MUSIC BUILDING", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "VOX", "Image": "path/to/image264.jpg" },
        { "Building Number": "SHC", "Location": "W J SPEECH/HEAR", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "SHC", "Image": "path/to/image265.jpg" },
        { "Building Number": "SHC", "Location": "W J SPEECH/HEAR", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "SHC", "Image": "path/to/image266.jpg" },
        { "Building Number": "WL", "Location": "WESTLAWN", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "WL", "Image": "path/to/image267.jpg" },
        { "Building Number": "WL", "Location": "WESTLAWN", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "WL", "Image": "path/to/image268.jpg" },
        { "Building Number": "WL", "Location": "WESTLAWN", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "WL", "Image": "path/to/image269.jpg" },
        { "Building Number": "WL", "Location": "WESTLAWN", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "WL", "Image": "path/to/image270.jpg" },
        { "Building Number": "R", "Location": "RIENOW HALL", "Room Number": "Omitted Information", "Directions": "Omitted Information for Security.", "Abbreviation": "R", "Image": "path/to/image271.jpg" },
    ];
    
    function displayRooms(rooms) {
        roomsList.innerHTML = '';
        rooms.forEach((room, index) => {
          const roomDiv = document.createElement('div');
          roomDiv.classList.add('room-item');
          roomDiv.innerHTML = `
            <h3>${room['Building Number']} - ${room.Abbreviation} - ${room.Location}</h3>
            <p>Room Number: ${room['Room Number']}</p>
            <button onclick="showDirections(${index})">Show Directions</button>
            <div id="directions-${index}" class="directions" style="display: none;">
              <p>${room.Directions}</p>
              <img src="${room.Image}" alt="Room Image">
            </div>
          `;
          roomsList.appendChild(roomDiv);
        });
      }
    
      displayRooms(roomsData);
    
      searchBar.addEventListener('keyup', function () {
        const searchTerm = searchBar.value.toLowerCase();
        const filteredRooms = roomsData.filter(room => {
          return (
            room.Location.toLowerCase().includes(searchTerm) ||
            room['Room Number'].toLowerCase().includes(searchTerm) ||
            room['Building Number'].toLowerCase().includes(searchTerm) ||
            room.Abbreviation.toLowerCase().includes(searchTerm)
          );
        });
        displayRooms(filteredRooms);
      });
    });
    
    function showDirections(index) {
      const directionsDiv = document.getElementById(`directions-${index}`);
      if (directionsDiv.style.display === 'none') {
        directionsDiv.style.display = 'block';
      } else {
        directionsDiv.style.display = 'none';
    }
}
    